name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Hugo example site and archive output
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build Hugo example site
        run: |
          cd exampleSite
          hugo --verbose --baseURL= --themesDir=../../

      - name: Upload Hugo example site
        uses: actions/upload-artifact@v4
        with:
          name: hugo-example-site
          path: exampleSite/public

  lighthouse:
    name: Run Lighthouse tests against built Hugo example site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Hugo example site
        uses: actions/download-artifact@v4
        with:
          name: hugo-example-site
          path: exampleSite/public

      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./lighthouserc.json
